spring.application.name=pieces-backend

spring.config.import=optional:file:./.env[.properties]

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/pieces_auto_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=THIS_IS_A_VERY_SECRET_KEY_FOR_PIECES_AUTO_BACKEND_2026_CHANGE_ME
jwt.expiration=86400000

app.upload.image-search-dir=uploads/image-search
app.upload.product-dir=uploads/products

app.base-url=http://localhost:8080

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.ai.image-service-url=http://localhost:8001/analyze
app.ai.image-similarity-url=http://localhost:8001/similarity
app.ai.image-embedding-url=http://localhost:8001/embedding

# Springdoc OpenAPI Config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha